# Generated by Django 6.0.5 on 2026-05-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_time', models.IntegerField()),
                ('adults', models.IntegerField()),
                ('stays_in_week_nights', models.IntegerField()),
                ('prediction', models.IntegerField()),
            ],
        ),
    ]
